"""
run_option1_sweep.py -- Sequential/parallel sweep of all Option 1 fuzzy-graph training runs

Iterates over every (sigma_combo, task) pair and calls retrain_gcn_mccv_generic.py
with --fuzzy-option 1 --edge-mode fuzzy_combined --fuzzy-subdir <combo>.

The sigma grid is 6×6 = 36 combos (sigmas 0.1/0.3/0.5/0.7/0.9/med for spatial × morph),
giving 36 × 3 tasks = 108 runs total.

Model saving during the sweep (--no-save-model, enabled by default):
  The sweep does not need a model per run (108 x 8 MB ~ 0.9 GB).
  By default the sweep passes --no-save-model to every run, so only metrics are kept:
    - per-run: {task}_mccv_{cfg}.csv, {task}_all_configs_test_results.json,
               BCNB_{task}_{cfg}_CA_predictions.csv, {task}_retrain_provenance_{winner}.json
  Once the post-sweep summary (sweep_top{N}_*.csv) identifies the best sigma combo,
  re-run that single combo without --no-save-model to obtain the definitive .pth:
    python scripts/training/retrain_gcn_mccv_generic.py \\
        --task 3class --fuzzy-option 1 --edge-mode fuzzy_combined \\
        --fuzzy-subdir sigmas_X_Y --device cuda
  Or use --save-model below to override and keep all .pth files (not recommended).

GPU benchmarks on TITAN Xp 12 GiB (3class, k=19, 5-fold × 3-repeat MC-CV):
    1 process  : ~370 s/fold   1.00 × throughput
    2 processes: ~410 s/fold   ~1.8 × throughput
    3 processes: ~426 s/fold   ~2.5 × throughput  ← recommended sweet spot
    4 processes: ~568 s/fold   ~2.5 × throughput  (GPU compute-saturated, no gain)
  Memory: ~1 GiB/process → 12 processes would fit in memory, but compute saturates at 3.
  GPU runs at 100 % utilisation / 177 W at N=3.

Logs per run:
    logs/option_1/<combo>/<task>/<task>_train.log

Launch in background (recommended):
    nohup python -u scripts/training/run_option1_sweep.py --task 3class --device cuda \\
        --parallel 3 > logs/option_1/sweep_master.log 2>&1 &

Other usage:
    # Preview all commands without running
    python scripts/training/run_option1_sweep.py --dry-run

    # Single task only
    python scripts/training/run_option1_sweep.py --task 3class --device cuda --parallel 3

    # Single sigma combo
    python scripts/training/run_option1_sweep.py --combo sigmas_0.5_0.5 --device cuda

    # Skip runs whose log already exists (resume after interruption)
    python scripts/training/run_option1_sweep.py --device cuda --parallel 3 --skip-existing

    # Keep .pth for every run (not recommended for full sweeps)
    python scripts/training/run_option1_sweep.py --device cuda --save-model
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timedelta
from itertools import product
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, '..'))
from _paths import *  # noqa: E402

RETRAIN_SCRIPT = os.path.join(_HERE, "retrain_gcn_mccv_generic.py")
LOGS_BASE = os.path.join(MOLSUB, "logs", "option_1")

# ---------------------------------------------------------------------------
# Sigma grid: one graph directory per (r_spatial, r_morphological) combination,
# generated by generate_fuzzy_sigma_grid.py
# ---------------------------------------------------------------------------
_LABELS = ["0.1", "0.3", "0.5", "0.7", "0.9", "med"]
ALL_COMBOS = [f"sigmas_{r_s}_{r_m}" for r_s, r_m in product(_LABELS, _LABELS)]  # 36

TASKS = ["2class", "3class", "4class"]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def log_path(combo: str, task: str) -> Path:
    return Path(LOGS_BASE) / combo / task / f"{task}_train.log"


def build_command(combo: str, task: str, device: str, extra: list[str]) -> list[str]:
    return [
        sys.executable, "-u", RETRAIN_SCRIPT,
        "--task",         task,
        "--device",       device,
        "--fuzzy-option", "1",
        "--edge-mode",    "fuzzy_combined",
        "--fuzzy-subdir", combo,
        *extra,
    ]


def fmt_duration(seconds: float) -> str:
    return str(timedelta(seconds=int(seconds)))


def timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def run_completed(lpath: Path) -> bool:
    """Return True only if the log file exists AND the run finished successfully (contains 'DONE.')."""
    if not lpath.exists():
        return False
    try:
        size = lpath.stat().st_size
        with open(lpath, "rb") as f:
            f.seek(max(0, size - 2048))
            tail = f.read().decode("utf-8", errors="replace")
        return "DONE." in tail
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Sequential runner
# ---------------------------------------------------------------------------

def run_sequential(jobs: list[tuple[str, str]], device: str, extra: list[str],
                   skip_existing: bool, dry_run: bool) -> tuple[int, int, int]:
    n_run = n_skip = n_fail = 0
    for combo, task in jobs:
        lpath = log_path(combo, task)
        cmd   = build_command(combo, task, device, extra)
        label = f"{combo}/{task}"

        if skip_existing and run_completed(lpath):
            print(f"  SKIP  {label}  (completed)", flush=True)
            n_skip += 1
            continue

        if dry_run:
            print(f"  CMD   {label}", flush=True)
            print(f"        log  → {lpath}", flush=True)
            print(f"        cmd  → {' '.join(cmd)}\n", flush=True)
            n_run += 1
            continue

        lpath.parent.mkdir(parents=True, exist_ok=True)
        print(f"  [{timestamp()}]  START  {label}", flush=True)
        t0 = time.time()

        with open(lpath, "w") as logf:
            logf.write(f"# cmd: {' '.join(cmd)}\n")
            logf.write(f"# started: {timestamp()}\n\n")
            logf.flush()
            result = subprocess.run(cmd, stdout=logf, stderr=logf)

        elapsed = time.time() - t0
        status = "OK" if result.returncode == 0 else f"FAIL(rc={result.returncode})"
        print(f"  [{timestamp()}]  {status:18s}  {label}  ({fmt_duration(elapsed)})",
              flush=True)

        if result.returncode != 0:
            n_fail += 1
        else:
            n_run += 1

    return n_run, n_skip, n_fail


# ---------------------------------------------------------------------------
# Parallel runner
# ---------------------------------------------------------------------------

def _launch(combo: str, task: str, device: str, extra: list[str]) -> tuple:
    """Open log file, launch subprocess, return (Popen, logfile_handle, t0)."""
    lpath = log_path(combo, task)
    lpath.parent.mkdir(parents=True, exist_ok=True)
    cmd = build_command(combo, task, device, extra)
    print(f"  [{timestamp()}]  START  {combo}/{task}", flush=True)
    logf = open(lpath, "w")
    logf.write(f"# cmd: {' '.join(cmd)}\n")
    logf.write(f"# started: {timestamp()}\n\n")
    logf.flush()
    p = subprocess.Popen(cmd, stdout=logf, stderr=logf)
    return p, logf, time.time()


def run_parallel(jobs: list[tuple[str, str]], max_workers: int, device: str,
                 extra: list[str], skip_existing: bool, dry_run: bool) -> tuple[int, int, int]:
    """
    Launch up to max_workers training processes concurrently.
    As each finishes, the next job in the queue is started.
    """
    n_run = n_skip = n_fail = 0

    if dry_run:
        # Fall back to sequential dry-run (no processes launched either way)
        return run_sequential(jobs, device, extra, skip_existing, dry_run=True)

    # Filter skip-existing up front so the queue is accurate
    pending = []
    for combo, task in jobs:
        if skip_existing and run_completed(log_path(combo, task)):
            print(f"  SKIP  {combo}/{task}  (completed)", flush=True)
            n_skip += 1
        else:
            pending.append((combo, task))

    # active: list of (Popen, logfile, t0, combo, task)
    active: list[tuple] = []
    job_iter = iter(pending)

    def fill_slots():
        while len(active) < max_workers:
            try:
                combo, task = next(job_iter)
            except StopIteration:
                break
            p, logf, t0 = _launch(combo, task, device, extra)
            active.append((p, logf, t0, combo, task))

    fill_slots()

    try:
        while active:
            time.sleep(5)
            finished = [(p, logf, t0, c, tk) for (p, logf, t0, c, tk) in active
                        if p.poll() is not None]
            for entry in finished:
                p, logf, t0, combo, task = entry
                active.remove(entry)
                logf.close()
                elapsed = time.time() - t0
                status = "OK" if p.returncode == 0 else f"FAIL(rc={p.returncode})"
                print(f"  [{timestamp()}]  {status:18s}  {combo}/{task}  ({fmt_duration(elapsed)})",
                      flush=True)
                if p.returncode != 0:
                    n_fail += 1
                else:
                    n_run += 1
                fill_slots()
    except KeyboardInterrupt:
        print(f"\n  [Ctrl+C] Terminating {len(active)} running processes...", flush=True)
        for p, logf, t0, combo, task in active:
            p.terminate()
            logf.close()
            print(f"    terminated {combo}/{task}", flush=True)
        raise

    return n_run, n_skip, n_fail


# ---------------------------------------------------------------------------
# Post-sweep summary
# ---------------------------------------------------------------------------

def summarize_sweep(tasks: list[str], top_n: int = 5) -> None:
    """Read all provenance JSONs and write a top-N CSV per task."""
    import csv

    results_base = os.path.join(MOLSUB, "results")
    option1_base = os.path.join(results_base, "option_1")
    out_dir = option1_base

    fields = [
        "rank", "task", "combo",
        "cv_mean_f1", "cv_std_f1",
        "test_accuracy", "test_f1", "test_auc", "n_patients",
        "cv_test_f1_gap",
        "knn", "sigma_spatial", "sigma_morphological",
    ]

    all_rows = []
    for task in tasks:
        rows = []
        combo_dirs = sorted(Path(option1_base).glob("sigmas_*/"))
        for combo_dir in combo_dirs:
            combo = combo_dir.name
            prov_files = list(combo_dir.glob(f"{task}/{task}_retrain_provenance_*.json"))
            if not prov_files:
                continue
            prov_path = max(prov_files, key=lambda p: p.stat().st_mtime)
            with open(prov_path) as f:
                p = json.load(f)
            arch = p.get("architecture", {})
            cv   = p.get("cv_results", {})
            test = p.get("test_results", {})
            cv_f1  = cv.get("mean_f1")
            tst_f1 = test.get("f1")
            # Real bandwidths of the combination, from the graphs' provenance
            graph_cfg_path = os.path.join(MOLSUB, "data", "BCNB", "results_graphs_november_23_fuzzy",
                                          combo, task, "k_19", "0_fuzzy_graph_config.json")
            graph_cfg = {}
            if os.path.exists(graph_cfg_path):
                with open(graph_cfg_path) as f:
                    graph_cfg = json.load(f)
            rows.append({
                "task":               task,
                "combo":              combo,
                "cv_mean_f1":         cv_f1,
                "cv_std_f1":          cv.get("std_f1"),
                "test_accuracy":      test.get("accuracy"),
                "test_f1":            tst_f1,
                "test_auc":           test.get("auc"),
                "n_patients":         test.get("n_patients"),
                "cv_test_f1_gap":     round(cv_f1 - tst_f1, 4) if (cv_f1 is not None and tst_f1 is not None) else None,
                "knn":                arch.get("knn"),
                "sigma_spatial":      graph_cfg.get("sigma_spatial"),
                "sigma_morphological": graph_cfg.get("sigma_morpho"),
            })

        rows.sort(key=lambda r: r["cv_mean_f1"] or 0, reverse=True)
        for rank, row in enumerate(rows[:top_n], start=1):
            all_rows.append({"rank": rank, **row})

        if rows:
            task_csv = os.path.join(out_dir, f"sweep_top{top_n}_{task}.csv")
            with open(task_csv, "w", newline="") as f:
                writer = csv.DictWriter(f, fieldnames=fields)
                writer.writeheader()
                writer.writerows([{"rank": r["rank"], **{k: r[k] for k in fields[1:]}}
                                   for r in all_rows if r["task"] == task])
            print(f"  Saved: {task_csv}", flush=True)

    # Combined CSV — only written when there are multiple tasks
    if len(tasks) > 1:
        tasks_label = "all_tasks" if set(tasks) == set(TASKS) else "_".join(tasks)
        combined_csv = os.path.join(out_dir, f"sweep_top{top_n}_{tasks_label}.csv")
        with open(combined_csv, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            writer.writerows(all_rows)
        print(f"  Saved: {combined_csv}", flush=True)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Sequential/parallel sweep of all Option 1 fuzzy training runs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--device", default="cpu",
                        help="PyTorch device (default: cpu)")
    parser.add_argument("--task", choices=TASKS, default=None,
                        help="Restrict to a single task (default: all three)")
    parser.add_argument("--combo", default=None,
                        help="Restrict to a single sigma combo, e.g. sigmas_0.5_0.5")
    parser.add_argument("--parallel", type=int, default=1, metavar="N",
                        help="Number of concurrent training processes (default: 1). "
                             "Recommended: 3 on TITAN Xp 12 GiB (GPU compute-saturated "
                             "at N=3; N=4 gives no throughput gain).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print commands and log paths without executing")
    parser.add_argument("--skip-existing", action="store_true",
                        help="Skip a run if its log file already exists")
    parser.add_argument("--epochs", type=int, default=None,
                        help="Override --epochs passed to retrain script")
    parser.add_argument("--patience", type=int, default=None,
                        help="Override --patience passed to retrain script")
    parser.add_argument("--cv-folds", type=int, default=None)
    parser.add_argument("--cv-repeats", type=int, default=None)
    parser.add_argument("--save-model", action="store_true",
                        help="Save the winner .pth for every run. Not recommended for full sweeps "
                             "(108 x 8 MB). By default --no-save-model is "
                             "passed to retrain_gcn_mccv_generic.py so only metrics are kept.")
    parser.add_argument("--summarize", action="store_true",
                        help="Only (re)generate the top-5 summary CSVs from existing provenance files, "
                             "without launching any training runs")
    parser.add_argument("--top-n", type=int, default=5, metavar="N",
                        help="Number of top combos to include in the summary (default: 5)")
    args = parser.parse_args()

    # Build optional passthrough flags
    extra = []
    if args.epochs   is not None: extra += ["--epochs",    str(args.epochs)]
    if args.patience is not None: extra += ["--patience",  str(args.patience)]
    if args.cv_folds is not None: extra += ["--cv-folds",  str(args.cv_folds)]
    if args.cv_repeats is not None: extra += ["--cv-repeats", str(args.cv_repeats)]
    if not args.save_model: extra += ["--no-save-model"]

    tasks  = [args.task]  if args.task  else TASKS

    if args.summarize:
        print(f"[{timestamp()}] Generating top-{args.top_n} summary from existing provenance files...",
              flush=True)
        summarize_sweep(tasks, top_n=args.top_n)
        return

    combos = [args.combo] if args.combo else ALL_COMBOS

    # Validate --combo
    if args.combo and args.combo not in ALL_COMBOS:
        parser.error(f"Unknown combo '{args.combo}'. Valid: {ALL_COMBOS}")

    if args.parallel < 1:
        parser.error("--parallel must be >= 1")

    jobs = [(combo, task) for combo in combos for task in tasks]
    total = len(jobs)

    print(f"[{timestamp()}] Option 1 sweep", flush=True)
    print(f"  Combos : {len(combos)}  Tasks : {len(tasks)}  Total runs : {total}", flush=True)
    print(f"  Device : {args.device}  Parallel : {args.parallel}", flush=True)
    if args.dry_run:
        print("  Mode   : DRY-RUN (nothing will be executed)\n", flush=True)

    sweep_t0 = time.time()

    if args.parallel == 1:
        n_run, n_skip, n_fail = run_sequential(
            jobs, args.device, extra, args.skip_existing, args.dry_run)
    else:
        n_run, n_skip, n_fail = run_parallel(
            jobs, args.parallel, args.device, extra, args.skip_existing, args.dry_run)

    total_elapsed = time.time() - sweep_t0
    print(f"\n[{timestamp()}] Sweep complete.", flush=True)
    print(f"  run={n_run}  skipped={n_skip}  failed={n_fail}  "
          f"total_time={fmt_duration(total_elapsed)}", flush=True)

    if not args.dry_run and n_run > 0:
        print(f"\n[{timestamp()}] Generating top-{args.top_n} summary...", flush=True)
        summarize_sweep(tasks, top_n=args.top_n)


if __name__ == "__main__":
    main()
